# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Build Windows Executable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    
    - name: Install dependencies
      run: |
        poetry install --no-root
    
    - name: Build with PyInstaller
      run: |
        source $VENV
        pyinstaller open-rewrite-windows-x64.spec
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: open-rewrite-windows-x64-${{ github.ref_name }}
        path: dist/
